#Nombre del Workflow
name: Merge Autom치tico de Jesus a Dev

#Definir los eventos que activar치n este workflow
on:
  workflow_dispatch:
  push:
    branches: ["Jesus"]

#Definir los trabajos que se van a realizar
jobs:
  merge-automatico:
    # Especificar el entorno en el cual correr치 la ejecuci칩n
    runs-on: ubuntu-latest

    #Pasos a realizar
    steps:
      #Paso 1.- Clonar el repositorio en el entorno
      - name: Clonar El Repositorio
        uses: actions/checkout@v3

      #Paso 2.- Configurar Git en el entorno
      - name: Configurar Git
        run: |
          git config --global user.name "JIELSAN"
          git config --global user.email "jesussjg811@gmail.com"
     
      #Paso 3.- Descargar todas las ramas en el entorno
      - name: Fetch all branches
        run: git fetch --all

      #Paso 3.- Ejecutar el merge
      - name: Merge De Jesus A Dev
        run: |
          git fetch origin Jesus
          git fetch origin Dev
          git checkout Dev
          git merge --no-ff Jesus -m "Merge Automatico De La Rama Jesus A Dev [skip ci]"
          git push origin Dev

      #Paso 4.- Mostrar el mensaje del merge
      - name: Notificacion Via GitHub Logs
        run: echo "El Merge De La Rama Jesus Con Su Rama De Origen Dev Fue Exitoso."
